{
  description = "Installable Nix package for Wyoming Voice Bridge";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  };

  # Usage: expose an installable default package for each supported Linux system.
  # Parameters: self is the flake source tree and nixpkgs provides the package set used for builds.
  # Return: an attrset whose packages.<system>.default value builds the Wyoming Voice Bridge application.
  outputs =
    { self, nixpkgs, ... }:
    let
      lib = nixpkgs.lib;
      systems = [
        "x86_64-linux"
        "aarch64-linux"
      ];

      # Usage: build the installable Wyoming Voice Bridge application for one supported system.
      # Parameters: system is the Nix system string used to import nixpkgs for the target platform.
      # Return: a buildPythonApplication derivation that installs the wyoming-voice-bridge launcher and runtime dependencies.
      mkPackage =
        system:
        let
          pkgs = import nixpkgs { inherit system; };
          pythonPackages = pkgs.python313Packages;
        in
        pythonPackages.buildPythonApplication {
          pname = "wyoming-voice-bridge";
          version = "0.1.0";
          pyproject = true;
          src = self;

          build-system = [ pythonPackages.hatchling ];
          dependencies = [
            pythonPackages.pyside6
            pythonPackages."pysilero-vad"
            pythonPackages.setuptools
          ];

          buildInputs = [
            pkgs.pipewire
            pkgs.qt6.qtbase
            pkgs.qt6.qtmultimedia
          ];
          nativeBuildInputs = [ pkgs.qt6.wrapQtAppsHook ];

          # Usage: forward the Qt runtime wrapper arguments into the Python script wrappers generated by buildPythonApplication.
          # Parameters: none.
          # Return: shell code that appends Qt environment variables to the wrapped wyoming-voice-bridge entry point.
          preFixup = ''
            makeWrapperArgs+=("''${qtWrapperArgs[@]}")
          '';

          pythonImportsCheck = [ "wyomingchat" ];

          meta = with pkgs.lib; {
            description = "Desktop bridge for local Wyoming STT and TTS services (Linux/PipeWire and Windows)";
            license = licenses.mit;
            mainProgram = "wyoming-voice-bridge";
            platforms = platforms.linux;
          };
        };
    in
    {
      packages = lib.genAttrs systems (
        system:
        {
          default = mkPackage system;
        }
      );
    };
}
